version: '3.8'

services:
  wms_db:
    image: mysql:8.0
    container_name: wms_db_local
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wms_db
      MYSQL_USER: wms_user
      MYSQL_PASSWORD: wms_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wms_app:
    build: .
    container_name: wms_backend
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=wms_db
      - DB_USER=wms_user
      - DB_PASSWORD=wms_password
      - DB_HOST=wms_db
      - DB_PORT=3306
      - DJANGO_ENV=development
    depends_on:
      wms_db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
