# Generated by Django 6.0.3 on 2026-03-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('weight_g', models.PositiveIntegerField(default=0, help_text='Hmotnost v gramech')),
                ('width_mm', models.PositiveIntegerField(default=0)),
                ('height_mm', models.PositiveIntegerField(default=0)),
                ('depth_mm', models.PositiveIntegerField(default=0)),
                ('is_3d_print_material', models.BooleanField(default=False)),
                ('is_textile', models.BooleanField(default=False)),
                ('is_packaging', models.BooleanField(default=False, help_text='Je toto samo o sobě krabice/fólie?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.client')),
                ('default_packaging', models.ForeignKey(blank=True, limit_choices_to={'is_packaging': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_packaging', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('material_type', models.CharField(blank=True, help_text='PLA, PETG, Bavlna...', max_length=50)),
                ('filament_length_m', models.FloatField(blank=True, help_text='Délka pro 3D tisk', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='core.product')),
            ],
        ),
    ]
