# Generated by Django 6.0.3 on 2026-07-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondetails',
            name='filament_length_m',
        ),
        migrations.AddField(
            model_name='productiondetails',
            name='filament_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hmotnost filamentu v gramech', max_digits=10, null=True),
        ),
    ]
