# Generated by Django 6.0.3 on 2026-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Název zakázky')),
                ('printer_type', models.CharField(default='Bambu Lab P1S', max_length=100, verbose_name='Typ tiskárny')),
                ('plates_count', models.PositiveIntegerField(default=1, verbose_name='Počet podložek (výměn)')),
                ('print_time_hours', models.FloatField(default=1.0, verbose_name='Čas tisku (hodiny)')),
                ('amortization_rate_per_hour', models.FloatField(default=25.0, verbose_name='Amortizace stroje (Kč/h)')),
                ('filament_type', models.CharField(default='PETG', max_length=50, verbose_name='Typ filamentu')),
                ('filament_weight_g', models.FloatField(verbose_name='Hmotnost filamentu ze sliceru (g)')),
                ('filament_kg_price', models.FloatField(default=500.0, verbose_name='Cena filamentu (Kč/kg)')),
                ('error_margin_multiplier', models.FloatField(default=1.05, help_text='Např. 1.10 = +10% materiálu na zmetky', verbose_name='Koeficient chybovosti')),
                ('modeling_hours', models.FloatField(default=0, verbose_name='Čas - 3D modelování (h)')),
                ('modeling_hourly_rate', models.FloatField(default=600, verbose_name='Sazba - 3D modelování (Kč/h)')),
                ('operation_hours', models.FloatField(default=0.1, verbose_name='Čas - Obsluha tiskárny (h)')),
                ('operation_hourly_rate', models.FloatField(default=300, verbose_name='Sazba - Obsluha tiskárny (Kč/h)')),
                ('postprocessing_hours', models.FloatField(default=0, verbose_name='Čas - Postprocessing (h)')),
                ('postprocessing_hourly_rate', models.FloatField(default=300, verbose_name='Sazba - Postprocessing (Kč/h)')),
                ('packaging_hours', models.FloatField(default=0.1, verbose_name='Čas - Balení (h)')),
                ('packaging_hourly_rate', models.FloatField(default=250, verbose_name='Sazba - Balení (Kč/h)')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Osobní vyzvednutí'), ('shipping', 'Zaslání poštou/kurýrem')], default='shipping', max_length=20, verbose_name='Způsob doručení')),
                ('shipping_cost', models.FloatField(default=100.0, verbose_name='Cena poštovného a balného (Kč)')),
                ('calculated_material_cost', models.FloatField(default=0, editable=False, verbose_name='Materiál celkem (Kč)')),
                ('calculated_amortization', models.FloatField(default=0, editable=False, verbose_name='Amortizace celkem (Kč)')),
                ('calculated_labor_cost', models.FloatField(default=0, editable=False, verbose_name='Práce celkem (Kč)')),
                ('calculated_total_price', models.FloatField(default=0, editable=False, verbose_name='CENA CELKEM (Kč)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nacenění 3D tisku',
                'verbose_name_plural': 'Výpočty nacenění 3D tisku',
            },
        ),
    ]
