# Generated by Django 6.0.3 on 2026-03-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printestimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název tiskárny (např. Bambu P1S)')),
                ('amortization_rate_per_hour', models.FloatField(default=25.0, verbose_name='Amortizace stroje (Kč/h)')),
            ],
            options={
                'verbose_name': 'Tiskárna',
                'verbose_name_plural': 'Flotila tiskáren',
            },
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='amortization_rate_per_hour',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='calculated_total_price',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='modeling_hours',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='operation_hours',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='packaging_hours',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='postprocessing_hours',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='print_time_hours',
        ),
        migrations.RemoveField(
            model_name='printestimation',
            name='printer_type',
        ),
        migrations.AddField(
            model_name='printestimation',
            name='calculated_base_cost',
            field=models.FloatField(default=0, editable=False, verbose_name='ČISTÝ NÁKLAD (Kč)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='calculated_price_100',
            field=models.FloatField(default=0, editable=False, verbose_name='Cena +100% (Kč)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='calculated_price_200',
            field=models.FloatField(default=0, editable=False, verbose_name='Cena +200% (Kč)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='calculated_price_350',
            field=models.FloatField(default=0, editable=False, verbose_name='Cena +350% (Kč)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='modeling_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Čas - 3D modelování (min)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='operation_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Čas - Obsluha tiskárny (min)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='packaging_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Čas - Balení (min)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='postprocessing_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Čas - Postprocessing (min)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='print_time_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Čas tisku (minuty)'),
        ),
        migrations.AddField(
            model_name='printestimation',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.printer', verbose_name='Tiskárna'),
        ),
    ]
