# Generated by Django 6.0.3 on 2026-07-28 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_filament_length_to_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondetails',
            name='filament_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hmotnost filamentu v gramech (min. 0 g)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
