# Generated by Django 6.0.7 on 2026-07-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_filament_weight_validator'),
        ('print3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_purchased',
            field=models.BooleanField(default=False, help_text='Nakupovaný produkt — nevzniká výrobní zakázka, pouze skladová položka'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Kolik kusů komponenty na 1 hotový produkt')),
                ('is_manufactured', models.BooleanField(default=True, help_text='True = vytvoří se ProductionOrder; False = jen vyskladnění ze skladu')),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Hmotnost filamentu v gramech', max_digits=10, null=True)),
                ('sku_position', models.CharField(blank=True, help_text='Pozice ve skladu (např. R3-P2)', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_component', to='core.product')),
                ('filament_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.filamentbrand')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.materialtype')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requirements', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Component (BOM)',
                'verbose_name_plural': 'Product Components (BOM)',
                'ordering': ['parent_product', 'sort_order'],
                'unique_together': {('parent_product', 'component')},
            },
        ),
    ]
