# Generated by Django 6.0.3 on 2026-03-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_printer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Printer', 'verbose_name_plural': 'Printer Fleet'},
        ),
        migrations.AlterField(
            model_name='printer',
            name='amortization_rate_per_hour',
            field=models.FloatField(default=25.0, verbose_name='Machine Amortization (CZK/h)'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Printer Name (e.g. Bambu P1S)'),
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('products_count', models.PositiveIntegerField(default=1, verbose_name='Products Count (Yield)')),
                ('plates_count', models.PositiveIntegerField(default=1, verbose_name='Plates Count (Changes)')),
                ('print_time_minutes', models.PositiveIntegerField(default=60, verbose_name='Print Time (minutes)')),
                ('filament_type', models.CharField(default='PETG', max_length=50, verbose_name='Filament Type')),
                ('filament_weight_g', models.FloatField(verbose_name='Filament Weight (g) from slicer')),
                ('filament_kg_price', models.FloatField(default=500.0, verbose_name='Filament Price (CZK/kg)')),
                ('error_margin_multiplier', models.FloatField(default=1.05, help_text='e.g. 1.10 = +10% material waste', verbose_name='Error Margin Multiplier')),
                ('modeling_minutes', models.PositiveIntegerField(default=0, verbose_name='Time - 3D Modeling (min)')),
                ('modeling_hourly_rate', models.FloatField(default=600, verbose_name='Rate - 3D Modeling (CZK/h)')),
                ('operation_minutes', models.PositiveIntegerField(default=5, verbose_name='Time - Printer Operation (min)')),
                ('operation_hourly_rate', models.FloatField(default=300, verbose_name='Rate - Printer Operation (CZK/h)')),
                ('postprocessing_minutes', models.PositiveIntegerField(default=0, verbose_name='Time - Postprocessing (min)')),
                ('postprocessing_hourly_rate', models.FloatField(default=300, verbose_name='Rate - Postprocessing (CZK/h)')),
                ('packaging_minutes', models.PositiveIntegerField(default=5, verbose_name='Time - Packaging (min)')),
                ('packaging_hourly_rate', models.FloatField(default=250, verbose_name='Rate - Packaging (CZK/h)')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Personal Pickup'), ('shipping', 'Shipping/Courier')], default='shipping', max_length=20, verbose_name='Delivery Type')),
                ('shipping_cost', models.FloatField(default=100.0, verbose_name='Shipping & Packaging Cost (CZK)')),
                ('calculated_material_cost', models.FloatField(default=0, editable=False, verbose_name='Total Material (CZK)')),
                ('calculated_amortization', models.FloatField(default=0, editable=False, verbose_name='Total Amortization (CZK)')),
                ('calculated_labor_cost', models.FloatField(default=0, editable=False, verbose_name='Total Labor (CZK)')),
                ('calculated_base_cost', models.FloatField(default=0, editable=False, verbose_name='Base Cost (0%)')),
                ('calculated_price_100', models.FloatField(default=0, editable=False, verbose_name='Price +100% Margin')),
                ('calculated_price_200', models.FloatField(default=0, editable=False, verbose_name='Price +200% Margin')),
                ('calculated_price_350', models.FloatField(default=0, editable=False, verbose_name='Price +350% Margin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'Custom Order',
                'verbose_name_plural': 'Custom Orders',
            },
        ),
        migrations.DeleteModel(
            name='PrintEstimation',
        ),
    ]
