# Generated by Django 6.0.3 on 2026-03-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_printer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Filament Name & Color')),
                ('type', models.CharField(default='PETG', max_length=50, verbose_name='Material Type')),
                ('kg_price', models.FloatField(default=500.0, verbose_name='Price per kg (CZK)')),
                ('error_margin_multiplier', models.FloatField(default=1.05, help_text='e.g. 1.05 = +5% waste', verbose_name='Error Margin Multiplier')),
            ],
            options={
                'verbose_name': 'Filament',
                'verbose_name_plural': 'Filament Inventory',
            },
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='error_margin_multiplier',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='filament_kg_price',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='filament_type',
        ),
        migrations.AddField(
            model_name='customorder',
            name='filament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filament', verbose_name='Filament'),
        ),
    ]
