# Generated by Django 6.0.7 on 2026-07-28 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_is_purchased_productcomponent'),
        ('print3d', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('shoptet', 'Shoptet')], max_length=30)),
                ('name', models.CharField(help_text="Např. 'Hlavní eshop', 'B2B shop'", max_length=255)),
                ('slug', models.SlugField(help_text='Používá se v URL webhooku: /webhook/<slug>/', unique=True)),
                ('base_url', models.URLField(help_text='Např. https://shop.example.com')),
                ('api_key', models.CharField(help_text='Consumer Key / API Key', max_length=255)),
                ('api_secret', models.CharField(help_text='Consumer Secret / API Secret', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Tajný klíč pro HMAC ověření webhooku (nepovinné)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Platform-specific nastavení (např. shopify_store_name)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_stores', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'E-commerce Store',
                'verbose_name_plural': 'E-commerce Stores',
                'ordering': ['organization', 'platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_order_id', models.BigIntegerField(help_text='ID objednávky v externím systému')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('billing_first_name', models.CharField(blank=True, max_length=255)),
                ('billing_last_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=50)),
                ('billing_address_1', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=255)),
                ('billing_postcode', models.CharField(blank=True, max_length=20)),
                ('billing_country', models.CharField(blank=True, max_length=100)),
                ('shipping_first_name', models.CharField(blank=True, max_length=255)),
                ('shipping_last_name', models.CharField(blank=True, max_length=255)),
                ('shipping_address_1', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(blank=True, max_length=255)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20)),
                ('shipping_country', models.CharField(blank=True, max_length=100)),
                ('shipping_method', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='CZK', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Kompletní payload z e-shopu')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_orders', to='core.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_orders', to='core.organization', verbose_name='Organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.ecommercestore')),
            ],
            options={
                'verbose_name': 'E-commerce Order',
                'verbose_name_plural': 'E-commerce Orders',
                'ordering': ['-imported_at'],
                'unique_together': {('store', 'platform_order_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_item_id', models.BigIntegerField(help_text='ID položky v externím systému')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Kompletní data položky z e-shopu')),
                ('ecommerce_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ecommerceorder')),
                ('product', models.ForeignKey(blank=True, help_text='Produkt ve WMS (podle SKU)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('ecommerce_order', 'ecommerce_item_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('qc', 'Quality Control'), ('packed', 'Packed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('qr_hash', models.CharField(default='PO-', max_length=50, unique=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.printer')),
                ('custom_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='print3d.customorder')),
                ('ecommerce_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='core.ecommerceorder')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='core.orderitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='core.organization', verbose_name='Organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='core.product')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.productionorder')),
            ],
            options={
                'verbose_name': 'Production Step',
                'verbose_name_plural': 'Production Steps',
                'ordering': ['production_order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('step_number', models.PositiveIntegerField()),
                ('media_url', models.URLField(blank=True, help_text='Obrázek nebo video instrukce')),
                ('is_required', models.BooleanField(default=True)),
                ('material_type', models.ForeignKey(blank=True, help_text='Specifické pro typ materiálu (None = univerzální)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.materialtype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='core.organization', verbose_name='Organization')),
                ('product', models.ForeignKey(blank=True, help_text='Specifické pro produkt (None = univerzální)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='core.product')),
            ],
            options={
                'verbose_name': 'Production Step Template',
                'verbose_name_plural': 'Production Step Templates',
                'ordering': ['step_number'],
            },
        ),
    ]
