# Generated by Django 6.0.3 on 2026-03-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_filament_remove_customorder_error_margin_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='filament',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='printer',
        ),
        migrations.DeleteModel(
            name='Filament',
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
