# Generated by Django 6.0.7 on 2026-07-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ecommercestore_ecommerceorder_orderitem_and_more'),
        ('print3d', '0004_merge_20260730_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='assigned_filament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='print3d.filament', verbose_name='Assigned Filament'),
        ),
    ]
