# Generated by Django 6.0.7 on 2026-08-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_assigned_filament_to_production_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceorder',
            name='date_paid',
            field=models.DateTimeField(blank=True, help_text='When payment was received', null=True),
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Order has been paid'),
        ),
        migrations.AlterField(
            model_name='ecommerceorder',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('on-hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=100),
        ),
    ]
