# Generated by Django 6.0.3 on 2026-04-21 13:27

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # Vytvoření základních skupin
    zakladni, _ = Group.objects.get_or_create(name='Základní tarif')
    manufacturing, _ = Group.objects.get_or_create(name='Manufacturing')
    tisk3d, _ = Group.objects.get_or_create(name='3D Tisk')
    
    # Přiřazení práv pro 3D Tisk (pokud existují modely Printer, Filament, CustomOrder)
    # Získání práv pro print3d modely
    print3d_perms = Permission.objects.filter(content_type__app_label='print3d')
    if print3d_perms.exists():
        tisk3d.permissions.set(print3d_perms)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_client_organization_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
