# Generated by Django 6.0.7 on 2026-08-01 06:12

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_groups(apps, schema_editor):
    """Create 4 predefined groups: Admin, Operátor, Obchoďák, Klient."""

    # ── Admin group (all permissions) ──
    admin_group, _ = Group.objects.get_or_create(name="Admin")
    all_permissions = Permission.objects.all()
    admin_group.permissions.set(all_permissions)

    # ── Operátor group ──
    operator_group, _ = Group.objects.get_or_create(name="Operátor")

    # Resolve content types lazily to avoid import issues
    content_types = {}
    for app_label, model in [
        ('core', 'productionorder'),
        ('core', 'productionstep'),
        ('print3d', 'filament'),
        ('print3d', 'printer'),
        ('print3d', 'customorder'),
    ]:
        try:
            content_types[(app_label, model)] = ContentType.objects.get(
                app_label=app_label, model=model
            )
        except ContentType.DoesNotExist:
            continue

    operator_permissions = []
    for (app_label, model), ct in content_types.items():
        if model in ('productionorder', 'productionstep'):
            operator_permissions.extend(
                Permission.objects.filter(content_type=ct, codename__in=[
                    f'view_{model}', f'change_{model}',
                ])
            )
        elif model in ('filament', 'printer', 'customorder'):
            operator_permissions.extend(
                Permission.objects.filter(content_type=ct, codename=f'view_{model}')
            )

    operator_group.permissions.set(operator_permissions)

    # ── Obchoďák group ──
    salesman_group, _ = Group.objects.get_or_create(name="Obchoďák")

    salesman_cts = {}
    for app_label, model in [
        ('print3d', 'customorder'),
        ('core', 'client'),
        ('core', 'product'),
    ]:
        try:
            salesman_cts[(app_label, model)] = ContentType.objects.get(
                app_label=app_label, model=model
            )
        except ContentType.DoesNotExist:
            continue

    salesman_permissions = []
    for (app_label, model), ct in salesman_cts.items():
        if model == 'customorder':
            salesman_permissions.extend(
                Permission.objects.filter(content_type=ct, codename__in=[
                    'add_customorder', 'change_customorder', 'view_customorder',
                ])
            )
        elif model in ('client', 'product'):
            salesman_permissions.extend(
                Permission.objects.filter(content_type=ct, codename=f'view_{model}')
            )

    salesman_group.permissions.set(salesman_permissions)

    # ── Klient group ──
    client_group, _ = Group.objects.get_or_create(name="Klient")

    try:
        customorder_ct = ContentType.objects.get(app_label='print3d', model='customorder')
        client_permissions = Permission.objects.filter(
            content_type=customorder_ct, codename='view_customorder'
        )
        client_group.permissions.set(client_permissions)
    except ContentType.DoesNotExist:
        pass


def remove_groups(apps, schema_editor):
    """Reverse: delete the 4 groups."""
    Group.objects.filter(name__in=["Admin", "Operátor", "Obchoďák", "Klient"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ecommerce_order_status_paid'),
        ('print3d', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]