# Generated by Django 6.0.7 on 2026-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished At'),
        ),
    ]
