# Generated by Django 6.0.3 on 2026-04-22 07:58

from django.db import migrations


def update_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    zakladni, _ = Group.objects.get_or_create(name='Základní tarif')
    
    # Pridani (add), Zmena (change) a Prohlizeni (view) pro jadrovy system, Mimo mazani
    action_prefixes = ('add_', 'change_', 'view_')
    core_models = ('client', 'product', 'productiondetails', 'organization')
    
    perms = Permission.objects.filter(
        content_type__app_label='core',
        content_type__model__in=core_models
    )
    
    assigned_perms = []
    for p in perms:
        if any(p.codename.startswith(prefix) for prefix in action_prefixes):
            assigned_perms.append(p)
            
    zakladni.permissions.add(*assigned_perms)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_default_groups'),
    ]

    operations = [
        migrations.RunPython(update_permissions),
    ]
