# Generated by Django 6.0.7 on 2026-07-15 11:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Material Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('recommended_settings', models.JSONField(blank=True, default=dict, help_text='JSON: nozzle_temp, bed_temp, speed, cooling, etc.', verbose_name='Recommended Settings')),
                ('default_error_margin', models.DecimalField(decimal_places=2, default=5.0, help_text='Default waste/spillage percentage for new spools', max_digits=5, verbose_name='Default Error Margin (%)')),
                ('default_drying_interval_days', models.IntegerField(blank=True, help_text='For future automatic drying reminders', null=True, verbose_name='Default Drying Interval (days)')),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Printer Name (e.g. Bambu P1S)')),
                ('amortization_rate_per_hour', models.FloatField(default=25.0, verbose_name='Machine Amortization (CZK/h)')),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printer Fleet',
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use brand price', max_digits=10, null=True, verbose_name='Price per kg Override (CZK)')),
                ('error_margin', models.DecimalField(decimal_places=2, default=5.0, help_text='Waste/spillage percentage', max_digits=5, verbose_name='Error Margin (%)')),
                ('sku', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=100, unique=True, verbose_name='SKU')),
                ('sku_position', models.CharField(blank=True, help_text='e.g. "R3-P2", manually assigned shelf position', max_length=50, null=True, verbose_name='SKU Position')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('stocked', 'Stocked'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('consumed', 'Consumed'), ('discarded', 'Discarded')], default='ordered', max_length=20, verbose_name='Status')),
                ('spool_size_kg', models.DecimalField(decimal_places=2, help_text='Pre-filled from brand', max_digits=4, verbose_name='Spool Size (kg)')),
                ('initial_net_weight_g', models.DecimalField(blank=True, decimal_places=2, help_text='Net filament weight upon receipt', max_digits=10, null=True, verbose_name='Initial Net Weight (g)')),
                ('current_net_weight_g', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-deducted from UsageLog on confirmed orders', max_digits=10, null=True, verbose_name='Current Net Weight (g)')),
                ('date_ordered', models.DateField(default=datetime.date.today, verbose_name='Date Ordered')),
                ('date_stocked', models.DateField(blank=True, null=True, verbose_name='Date Stocked')),
                ('vacuum_sealed', models.BooleanField(default=False, verbose_name='Vacuum Sealed')),
                ('date_opened', models.DateField(blank=True, null=True, verbose_name='Date Opened')),
                ('last_dried', models.DateTimeField(blank=True, null=True, verbose_name='Last Dried')),
                ('next_drying', models.DateTimeField(blank=True, null=True, verbose_name='Next Drying (Reminder)')),
                ('diameter_checked', models.BooleanField(default=False, verbose_name='Diameter Checked')),
                ('diameter_check_date', models.DateField(blank=True, null=True, verbose_name='Diameter Check Date')),
                ('diameter_result', models.CharField(blank=True, help_text='e.g. "1.74 ±0.03"', max_length=50, null=True, verbose_name='Diameter Result')),
                ('rewound', models.BooleanField(default=False, verbose_name='Rewound')),
                ('rewound_date', models.DateField(blank=True, null=True, verbose_name='Rewound Date')),
                ('qr_code', models.CharField(blank=True, help_text='Auto-generated unique hash/ID', max_length=64, unique=True, verbose_name='QR Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Filament',
                'verbose_name_plural': 'Filament Inventory',
                'ordering': ['brand__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('products_count', models.PositiveIntegerField(default=1, verbose_name='Products Count (Yield)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status')),
                ('plates_count', models.PositiveIntegerField(default=1, verbose_name='Plates Count (Changes)')),
                ('print_time_minutes', models.PositiveIntegerField(default=60, verbose_name='Print Time (minutes)')),
                ('filament_weight_g', models.FloatField(verbose_name='Filament Weight (g) from slicer')),
                ('modeling_minutes', models.PositiveIntegerField(default=0, verbose_name='Time - 3D Modeling (min)')),
                ('modeling_hourly_rate', models.FloatField(default=600, verbose_name='Rate - 3D Modeling (CZK/h)')),
                ('operation_minutes', models.PositiveIntegerField(default=5, verbose_name='Time - Printer Operation (min)')),
                ('operation_hourly_rate', models.FloatField(default=300, verbose_name='Rate - Printer Operation (CZK/h)')),
                ('postprocessing_minutes', models.PositiveIntegerField(default=0, verbose_name='Time - Postprocessing (min)')),
                ('postprocessing_hourly_rate', models.FloatField(default=300, verbose_name='Rate - Postprocessing (CZK/h)')),
                ('packaging_minutes', models.PositiveIntegerField(default=5, verbose_name='Time - Packaging (min)')),
                ('packaging_hourly_rate', models.FloatField(default=250, verbose_name='Rate - Packaging (CZK/h)')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Personal Pickup'), ('shipping', 'Shipping/Courier')], default='shipping', max_length=20, verbose_name='Delivery Type')),
                ('shipping_cost', models.FloatField(default=100.0, verbose_name='Shipping & Packaging Cost (CZK)')),
                ('calculated_material_cost', models.FloatField(default=0, editable=False, verbose_name='Total Material (CZK)')),
                ('calculated_amortization', models.FloatField(default=0, editable=False, verbose_name='Total Amortization (CZK)')),
                ('calculated_labor_cost', models.FloatField(default=0, editable=False, verbose_name='Total Labor (CZK)')),
                ('calculated_base_cost', models.FloatField(default=0, editable=False, verbose_name='Base Cost (0%)')),
                ('calculated_price_100', models.FloatField(default=0, editable=False, verbose_name='Price +100% Margin')),
                ('calculated_price_200', models.FloatField(default=0, editable=False, verbose_name='Price +200% Margin')),
                ('calculated_price_350', models.FloatField(default=0, editable=False, verbose_name='Price +350% Margin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.filament', verbose_name='Filament')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print3d.printer', verbose_name='Printer')),
            ],
            options={
                'verbose_name': 'Custom Order',
                'verbose_name_plural': 'Custom Orders',
            },
        ),
        migrations.CreateModel(
            name='FilamentBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('spool_size_kg', models.DecimalField(choices=[(0.5, '0.5 kg'), (1.0, '1.0 kg'), (2.5, '2.5 kg'), (5.0, '5.0 kg')], decimal_places=2, max_digits=4, verbose_name='Spool Size (kg)')),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='EAN Code')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='Photo URL')),
                ('test_notes', models.TextField(blank=True, help_text='Temperature tower, print settings, results', null=True, verbose_name='Test Notes')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Price per kg (CZK)')),
                ('color_hex', models.CharField(blank=True, help_text='e.g. #FF5733', max_length=7, null=True, verbose_name='Color (HEX)')),
                ('spool_weight_g', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the empty spool — measured once, valid for all spools of this brand', max_digits=7, null=True, verbose_name='Empty Spool Weight (g)')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to archive obsolete brands', verbose_name='Active')),
                ('test_filament', models.OneToOneField(blank=True, help_text='Reference to a tested spool of this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_test_for', to='print3d.filament', verbose_name='Test Filament')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='print3d.materialtype', verbose_name='Material Type')),
            ],
            options={
                'verbose_name': 'Filament Brand',
                'verbose_name_plural': 'Filament Brands',
                'ordering': ['name', 'material_type__name'],
            },
        ),
        migrations.AddField(
            model_name='filament',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filaments', to='print3d.filamentbrand', verbose_name='Brand'),
        ),
        migrations.CreateModel(
            name='FilamentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grams Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_usage_logs', to='print3d.customorder', verbose_name='Custom Order')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='print3d.filament', verbose_name='Filament')),
            ],
            options={
                'verbose_name': 'Filament Usage Log',
                'verbose_name_plural': 'Filament Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
