# Generated by Django 6.0.7 on 2026-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorder',
            options={'verbose_name': 'B2B order', 'verbose_name_plural': 'B2B orders'},
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
    ]
