# Generated by Django 6.0.7 on 2026-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='spool_size_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-filled from brand', max_digits=4, verbose_name='Spool Size (kg)'),
        ),
    ]
