# Generated by Django 6.0.3 on 2026-04-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_client_organization_and_more'),
        ('print3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='core.organization'),
        ),
        migrations.AddField(
            model_name='filament',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filaments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='printer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.organization'),
        ),
    ]
