# Generated by Django 5.2.16 on 2026-07-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print3d', '0002_alter_customorder_options_alter_customorder_status'),
        ('print3d', '0003_alter_filament_spool_size_kg'),
    ]

    operations = [
    ]
