# Generated by Django 6.0.7 on 2026-07-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print3d', '0004_merge_20260730_0700'),
        ('print3d', '0007_fix_null_organization_ids'),
    ]

    operations = [
    ]
