# Generated by Django 6.0.7 on 2026-08-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_user_groups'),
        ('print3d', '0008_merge_20260730_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='access_code',
            field=models.CharField(blank=True, help_text='Bambu access code / PrusaLink token', max_length=255, verbose_name='Access Code'),
        ),
        migrations.AddField(
            model_name='printer',
            name='brand',
            field=models.CharField(choices=[('bambu', 'Bambu Lab'), ('prusa', 'Prusa'), ('klipper', 'Klipper')], default='bambu', max_length=20, verbose_name='Printer Brand'),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(blank=True, help_text='LAN IP pro komunikaci', max_length=45, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='printer',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Kdy tiskárna naposledy komunikovala', null=True, verbose_name='Last Seen'),
        ),
        migrations.AddField(
            model_name='printer',
            name='serial',
            field=models.CharField(blank=True, help_text='Bambu serial (topic device/<serial>/...)', max_length=100, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('printing', 'Printing'), ('paused', 'Paused'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='idle', help_text='Aktuální stav (sladěno s MQTT)', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('printing', 'Printing'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=0, help_text='Řazení fronty (vyšší = dřív)', verbose_name='Priority')),
                ('progress', models.IntegerField(default=0, help_text='0–100, z MQTT', verbose_name='Progress (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('filament_used_g', models.DecimalField(blank=True, decimal_places=2, help_text='Spotřeba z MQTT (jen telemetrie)', max_digits=8, null=True, verbose_name='Filament Used (g)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('printer', models.ForeignKey(blank=True, help_text='Na které tiskárně', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='print3d.printer', verbose_name='Printer')),
                ('production_order', models.ForeignKey(blank=True, help_text='Co se tiskne', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='core.productionorder', verbose_name='Production Order')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-priority', '-pk'],
            },
        ),
    ]
